### ISSUE TITLE
Format does not change files when .sln path contains spaces

### ISSUE THREAD

**Issue by ChrisBertrand** [sethreno/ReGitLint#1]
I run

`ReGitLint.exe format -s "PATH TO SLN.sln" -f Modified `

but don't see CleanupCode making any changes.

```
JetBrains Cleanup Code 2020.1.3
Running in 64-bit mode, .NET runtime 4.0.30319.42000 under Microsoft Windows NT 6.2.9200.0
Usage: CleanupCode.exe [options] [project file]
Show help: CleanupCode.exe --help
PM> 
```

If I add -d to the end, it says...

```
!!!! Process Aborted !!!!
Code formatter changed the following files:
 * /Models/File.cs
PM> 
```

So I can see it knows what to change, it just never seems to alter the file.

Anything I'm missing?

**Comment by sethreno** [comment]
I'm not sure what's going on there. Would you mind attaching Models/File.cs?

**Comment by ChrisBertrand** [comment]
Hi Seth,

I can't post the original source, but this is a shortened obfuscated file that has the same issues.
```

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using Core.Enums;

namespace Core.Models
{
    public class Record
    {
        [Key]
        [MaxLength(50)]
        public string Id { get; set; }

        [Key][MaxLength(128)]
        public string Name { 
		get;
		set; 
		}
	}
}
```

using cleanupcode directly will fix the formatting problems and organise properties etc in name order. The tool currently just leaves the file untouched.

**Comment by ChrisBertrand** [comment]
Hey Seth, I've pulled down the code and found the issue. I've raised a PR #2 Please let me know if this looks ok.

**Comment by sethreno** [comment]
@ChrisBertrand Thanks for fixing this. It's been merged. I'll get a new version deployed to nuget later today.

**Comment by sethreno** [comment]
This is fixed in version 1.5.2 which is on nuget now.

**Comment by ChrisBertrand** [comment]
Amazing thanks Seth!

**Comment by sethreno** [comment]
You're welcome. Thanks again for the pull request. If you find ReGitLint
useful please give it a star. :)
