### ISSUE TITLE
Relative PATH issue

### ISSUE THREAD

**Issue by mr-fedorof** [sethreno/ReGitLint#10]
Hi!

I have the following folder structure:
- sln_folder/MySolution.sln
- sln_folder/TestClass.cs

`dotnet regitlint -f staged` and `dotnet regitlint -f modified` don't work for this folder structure.
And it doesn't matter if I run the tool from the **root** or from the **sln_folder** folder.

Files in --include option (used --print-command option) always have absolute path from the root, but it should be relative to the solution.

I would appreciate it if you can fix this issue.
Thanks.

**Comment by Jipperism** [comment]
Hi!

I'm running into the same issue. I've spend some time investigating, and came up with the following summary:

Folder structure:

- `sln_folder/MySolution.sln`
- `sln_folder/sub_folder/Program.cs`

Running

`dotnet regitlint --print-command --solution-file="./sln_folder/MySolution.sln" -f staged`

prints the following command.

`dotnet tool run jb cleanupcode "./sln_folder/MySolution.sln"  --include=";/sub_folder/Program.cs" --profile="Built-in: Full Cleanup" -dsl=GlobalAll -dsl=SolutionPersonal -dsl=ProjectPersonal`

which fails to find any files.

Instead, the file paths passed to the `--include` flag should be relative to the solution file, eg `";./sub_folder/Program.cs`.

Would love to add this to our project as a git hook if we manage to fix this.

**Comment by Jipperism** [comment]
My guess would be that this is where a `.` has to be prefixed under certain conditions (solution file not in `.git` top level directory).

https://github.com/sethreno/ReGitLint/blob/8515528460aafd6c2a7118a110525df322497af5/ReGitLint/Cleanup.cs#L153-L154

**Comment by sethreno** [comment]
I've tried to implement a fix for this but haven't had any luck. I've reproduced the directory structure you describe but `;./sub_folder/Program.cs `doesn't work. Will you post a working `dotnet jb cleanupcode --include` command line example?

**Comment by sethreno** [comment]
I kind of hacked this by prefixing all files with "**/". That seems to work for both cases where .sln files are in the root and when they are in a peer directory to the projects. if you figure out the jb cleanupcode command to run that works please let me know so I can remove the hack.

**Comment by sethreno** [comment]
The fix is in 6.0.3
