### ISSUE TITLE
Is there a way to skip build?

### ISSUE THREAD

**Issue by vdurante** [sethreno/ReGitLint#11]
Sorry, I know this issue is not related to ReGitLint, but I am quite desperate and I believe you could know the solution. Do you know if there is a way of skipping build on `jb cleanupcode`? The build is taking too much time and I would like to skip it.

Thank you!

**Comment by sethreno** [comment]
I don't think there is a way to skip the build. You might try the --format-only option and see if that speeds it up. 

I feel your pain though, I hate how slow it is. I just can't find anything better.
