### ISSUE TITLE
Bug: Not all settings layers are ignored

### ISSUE THREAD

**Issue by bart-degreed** [sethreno/ReGitLint#13]
The following code at https://github.com/sethreno/ReGitLint/blob/master/ReGitLint/Cleanup.cs#L327-L333:

```c#
            if (!jbArgs.Contains("-dsl")
                && !jbArgs.Contains("--disable-settings-layers")) {
                // ignore settings that might conflict with .editorconfig
                jbArgs.Add("-dsl=GlobalAll");
                jbArgs.Add("-dsl=SolutionPersonal");
                jbArgs.Add("-dsl=ProjectPersonal");
            }
```

does not clear all machine-wide and personal settings layers. See https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/1104 for details. It appears that `-dsl=GlobalPerProduct` is missing in this list (see https://www.jetbrains.com/help/resharper/CleanupCode.html).

Edit: removed suggestion to use `--no-buildin-settings`, because it does achieve the desired effect.

**Comment by sethreno** [comment]
Thanks for reporting. This is fixed in 6.0.1
