### ISSUE TITLE
Feature request: allow diff against commit hash (range), including staged/unstaged changes

### ISSUE THREAD

**Issue by bart-degreed** [sethreno/ReGitLint#15]
Today cleanup can be run on either staged files (`-f staged`), modified files in the working tree (`-f modified`), the set of changed files in a single commit (`-a 3796556`), or the set of changed files between two commits (`-a 6708090 -b 3796556`).

I would like to be able to run against the set of changed files in one or more commits, plus the set of staged and the set of unstaged files.

This speeds up local development, compared to running a full cleanup. I would pass the commit hash of the base branch and HEAD, so that it reformats all files in those commits plus the files (staged/unstaged) that I'm still working on.

**Comment by sethreno** [comment]
Thanks Bart, this is a cool idea! I'm thinking of adding new options to support this without breaking the existing cli. Something like..

    --staged
    --modified
    --commit

`--commit` would support multiple and support a range using `:`

For example:

    regitlint --staged --modified --commit HEAD --commit 840f0 --commit e431f:32976

What do you think?

**Comment by bart-degreed** [comment]
Perhaps I'm missing something, but I don't see why you need new switches for this. I think you can just reuse the existing ones:
```
-f staged -f modified -a 6708090 -b 3796556
```

Internally, it would build a set of unique files by processing each switch in order, instead of requiring just one switch.
