### ISSUE TITLE
Bug: "-f modified" does not include new (untracked) files

### ISSUE THREAD

**Issue by bart-degreed** [sethreno/ReGitLint#16]
When using the `-f modified` flag, this translates to the next command:
```bash
git diff --name-only
```
which lists modified and deleted files, but does not include newly added files. I found that the next command does list all three types:
```bash
git ls-files --others --exclude-standard --modified
```

**Comment by sethreno** [comment]
Fixed this in the latest version. Thanks for reporting and providing the needed git command.
