### ISSUE TITLE
Feature request: Enable use of Global Resharper Commandline Tools

### ISSUE THREAD

**Issue by fehrm** [sethreno/ReGitLint#19]
Hi, 
On line 330 in Cleanup.cs you check if the tool is installed locally. 
https://github.com/sethreno/ReGitLint/blob/8cb9ec09b797ecfc5d2beade8589c8c915bc128e/ReGitLint/Cleanup.cs#L330 

For some Teams it is a matter of dispute on whether or not you want to run Resharper in Visual Studio or only through commandline. In those cases it would be helpful if ReGitLint could fall back to use the Globally installed (dotnet tool install -g) version of Resharper jb tool. That way you don't need to explicitly install the tool manifest in every repo as well.

**Comment by sethreno** [comment]
This is fixed in 6.0.8
