### ISSUE TITLE
Add the flag no-build

### ISSUE THREAD

**Issue by OS-antoniocaeiro** [sethreno/ReGitLint#41]
Can we add the jb no-build flag to this?
--no-build : Do not build solution before processing (default: False).
from jb cleanupcode --help

**Comment by bkoelman** [comment]
See the root readme. `--jb --no-build` should work.

**Comment by namtab00** [comment]
@bkoelman hi, sorry for the issue resurrect. I've tried what you've suggested, but the solution is still being built.

Is there some way for regitlint to output the precise `dotnet jb cleanupcode` command it is issuing?

**Comment by bkoelman** [comment]
There is, but it's probably easier to look at the source code rather than asking these questions.

**Comment by namtab00** [comment]
Ok, I'll try, thank you for your time.
