### ISSUE TITLE
Support specifying a code cleanup profile

### ISSUE THREAD

**Issue by namtab00** [sethreno/ReGitLint#42]
Maybe I haven't understood correctly all instructions, but it seems there is no support for providing a code cleanup profile to apply.

I've currently used these one-time commands to globally perform code cleanup with the JetBrains donet jb codecleanup global tool:
```powershell
# install dotnet global tool if missing
dotnet tool install -g JetBrains.ReSharper.GlobalTools

# see code cleanup syntax
jb cleanupcode --help

$slnDir = "C:\Development\repo\SolutionFolder"
$slnFile = "SolutionFileName.sln"
$codeCleanupProfileName = "ProfileName"

cd $slnDir

# run code cleanup
jb cleanupcode --profile=$codeCleanupProfileName --include="SubFolder/**/*.cs" --exclude="**/*.designer.*;**/Migrations/**/*.cs" $slnFile
```

I'd love to setup a pre-commit hook to share with my team, and ReGitLint seems pretty useful to that goal, but I would need it to support specifying a code cleanup profile name.

**Comment by bkoelman** [comment]
It looks like you're missing a space in the last command before --include.

**Comment by namtab00** [comment]
> It looks like you're missing a space in the last command before --include.

yeah, fixed it

still, I was just sharing the powershell script I've run manually to format my solution...

the question is how would I use regitlint with a specific shared (in committed .DotSettings) code cleanup profile.

**Comment by bkoelman** [comment]
See example at https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/Build.ps1#L54

**Comment by namtab00** [comment]
Thank you, that should do it, I'll try it asap.
