### ISSUE TITLE
disable the formatter with using library. 

### ISSUE THREAD

**Issue by worldleadertechSteven** [sethreno/ReGitLint#6]
In my project, there are something library created by myself, how to disable the formatter with using System; or using System.Web.Routing; or others ? My project has a lot of folders and files, please provide the command line methods to help me to handle this issues.

**Comment by sethreno** [comment]
Hi Steven,

Excluding files is a function of the jet brains code cleanup tool. You can read about all the options [here](https://www.jetbrains.com/help/resharper/CleanupCode.html#cleanup-parameters). 

Options can be passed through from regitlint to the jet brains tool using the `--jb` option. Here's an example:

    dotnet regitlint --jb --exclude="**/*.html"

You can also disable formatting for a specific file or section of a file using a formatter directive comment. Here's an example:

    // @formatter:off— disable formatter after this line
    ... (some code here)
    // @formatter:on— enable formatter after this line
